const words = [
  { hint: 'Camaro ...  ♫', word: 'amarelo', category: 'cor' },
  { hint: 'Pode ser federal', word: 'escola', category: 'local' },
  { hint: 'Comumente personalizada', word: 'caneca', category: 'objeto' },
  { hint: 'Considerado um expert', word: 'perito', category: 'profissao' },
  { hint: 'Moda', word: 'paris', category: 'capital' },
  { hint: 'Tamo tipo ...  ♫', word: 'passarinho', category: 'animal' },
  { hint: 'Define listas e arrays', word: 'colchete', category: 'caractere' },
  { hint: '7 x _', word: 'alemanha', category: 'pais' },
  { hint: 'Pode ser de casal', word: 'cama', category: 'objeto' },
  { hint: 'Feita de frutas', word: 'geleia', category: 'alimento' },
  { hint: 'Big Ben', word: 'londres', category: 'capital' },
  { hint: 'Combate', word: 'boxe', category: 'esporte' },
  { hint: 'Garoto de programa', word: 'programador', category: 'profissao' },
  { hint: 'Hermanos', word: 'argentina', category: 'pais' },
  { hint: 'Natureza', word: 'parque', category: 'local' },
  { hint: 'Pode ser uma flor', word: 'violeta', category: 'cor' },
  { hint: 'Muro', word: 'berlim', category: 'capital' },
  { hint: 'Roedor', word: 'capivara', category: 'animal' },
  { hint: 'Polemico (eu odeio)', word: 'pequi', category: 'alimento' },
  { hint: 'Corrijo frases', word: 'asterisco', category: 'caractere' },
  { hint: 'Cascao odeia', word: 'chuveiro', category: 'objeto' },
  { hint: 'Carnaval', word: 'brasil', category: 'pais' },
  { hint: 'Muito rapido', word: 'coelho', category: 'animal' },
  { hint: 'Comum na Igreja Catolica', word: 'sino', category: 'objeto' },
  { hint: 'Muito comum em rostos', word: 'castanho', category: 'cor' },
  { hint: 'Medicina', word: 'endocrinologista', category: 'profissao' },
  { hint: 'Famoso em redes sociais', word: 'cerquilha', category: 'caractere' },
  { hint: 'Centro comercial', word: 'shopping', category: 'local' },
  { hint: 'Luxo', word: 'dubai', category: 'capital' },
  { hint: 'Muito famoso nos EUA', word: 'basquete', category: 'esporte' },
  { hint: 'Pequena e assada', word: 'esfirra', category: 'alimento' },
  { hint: 'Pastel de belem', word: 'portugal', category: 'pais' },
  { hint: 'Relacionada a sensualidade', word: 'magenta', category: 'cor' },
  { hint: 'O melhor amigo do homem', word: 'cachorro', category: 'animal' },
  { hint: 'Coliseu', word: 'roma', category: 'capital' },
  { hint: 'Voltado para diversao', word: 'boate', category: 'local' },
  { hint: 'Resolve conflitos', word: 'juiz', category: 'profissao' },
  { hint: 'Famoso em barbearias', word: 'navalha', category: 'objeto' },
  { hint: 'Mais praticado no mundo', word: 'futebol', category: 'esporte' },
  { hint: 'Populoso', word: 'china', category: 'pais' },
];

export default words;
