const words = [
  { word: 'amarelo', category: 'cor' },
  { word: 'escola', category: 'local' },
  { word: 'caneca', category: 'objeto' },
  { word: 'perito', category: 'profissao' },
  { word: 'colchete', category: 'caractere' },
  { word: 'passarinho', category: 'animal' },
  { word: 'cama', category: 'objeto' },
  { word: 'geleia', category: 'alimento' },
  { word: 'boxe', category: 'esporte' },
  { word: 'quiroprata', category: 'profissao' },
  { word: 'parque', category: 'local' },
  { word: 'violeta', category: 'cor' },
  { word: 'texugo', category: 'animal' },
  { word: 'pequi', category: 'alimento' },
  { word: 'asterisco', category: 'caractere' },
  { word: 'chuveiro', category: 'objeto' },
  { word: 'coelho', category: 'animal' },
  { word: 'sino', category: 'objeto' },
  { word: 'castanho', category: 'cor' },
  { word: 'endocrinologista', category: 'profissao' },
  { word: 'cerquilha', category: 'caractere' },
  { word: 'shopping', category: 'local' },
  { word: 'basquete', category: 'esporte' },
  { word: 'esfirra', category: 'alimento' },
  { word: 'magenta', category: 'cor' },
  { word: 'cachorro', category: 'animal' },
  { word: 'boate', category: 'local' },
  { word: 'juiz', category: 'profissao' },
  { word: 'navalha', category: 'objeto' },
  { word: 'futebol', category: 'esporte' },
];

export default words;
